### ISSUE TITLE
Template WIP with badge laser Usage1

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/pack-openbadge-fablab#15]
![image](https://user-images.githubusercontent.com/12049360/44626938-f5f29500-a925-11e8-8f2d-6209edef42ad.png)

source
https://github.com/nicolasdb/nicolasdb.github.io/issues/81

**Comment by nicolasdb** [comment]
https://github.com/zuperninja/WIP/blob/master/OpenFab/Gamification/referentiel-pedagogique.md

## Objective
- Clarification of skills and how to earn it
- Common base between fablabs
- Contributing through documentation.
- Facilitate exploration

### Use
3 steps to validate your skill :
- apprendre // learn : Peer2Peer, Someone show me how to do it, I'm taking note
- faire // make : I doing it myself, and I'm taking note of what I discover/ what did I forgot from before
- partager // share : it's my turn to share what I know. Even by writing a complete tutorial or by showing how to do, Peer2Peer.

### how
Documentation can be, to begin with, pictures, paper notes or online; whatever the platform of you choose.
@openfab-lab, we are using github and github-page

And from the beginning, we encourage to use this format. (page for passport maker)

![pageprotostep](https://user-images.githubusercontent.com/12049360/44627268-30126580-a92b-11e8-8b25-7b8f56a4cfb3.png)
https://github.com/openfab-lab/passeportMaker/tree/master/00template

- Contexte // Context
- Objectif // Goal
- Proposition // Process

Which is base on [Non Violent Communication](https://en.wikipedia.org/wiki/Nonviolent_Communication#Four_components) and [github guidelines](https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution). 

>Communicating effectively
Whether you’re a one-time contributor or trying to join a community, working with others is one of the most important skills you’ll develop in open source.

**Comment by nicolasdb** [comment]
![skillstree](https://user-images.githubusercontent.com/12049360/44899511-442ade00-ad02-11e8-8e9e-bb306588ef6a.jpg)

![image](https://user-images.githubusercontent.com/12049360/44627496-4de1c980-a92f-11e8-9810-dead008b373e.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/44627542-ed06c100-a92f-11e8-98dd-b81c253ebf6f.png)

**Comment by nicolasdb** [comment]
1. Utilisation machine
  1.1 CO2
  1.1.1 lasersaur (Openfab)
  1.1.2 Epilog (?.)
  1.1.3 BCN3D Ignis (fablab'ke)
  1.2 Diode
  1.2.1 mini A5
  1.2.2 Eleksmaker A3
2. Utilisation software machine
  2.1 Lasaurapp or driveapp (lasersaur)
  2.2 Laserweb 4

**Comment by nicolasdb** [comment]
Badge tech 1

Entretient, et nettoyage de la machine; 
Vérifier les optiques, les nettoyer
Check du compresseur
Le filtre à air


tech 2
calibration optique

tech 3
remplacement de pièces. 
- tube laser
- lit honeycomb
- roulement

**Comment by nicolasdb** [comment]
# Pratiquons! 
## Test 1 - Nicolasdb
Afin de démontrer mon art au laser. pwupwupwu. 
J'ai produit 64 coins de 5 crrr. Issue par là https://github.com/nicolasdb/nicolasdb.github.io/issues/105
Je démontre ainsi ma maîtrise de l'outil càd: 
- [x] J'ai compris les réglages Focus, Feed et power. 
- [x] J'ai compris le on/off de la machine et ses sécurités. 
- [x] J'ai compris les différences entre gravures, découpes IN et découpe OUT ainsi que la gestion du recto verso.
- [x] + a nice bonus, j'ai bien compris comment travailler au pochoir avec le laser. 
### Reward: 
My badge.  🥇 
Next time, I'll be able to earn some credits instead.

**Todo:** 
I'll make an article on my portfolio to brag about it online, b**ch.


note de l'auteur: 
Donc, 
1. une issue pour prendre des notes. 
2. un post pour publier.

Est-ce qu'on passerai pas par un pull request quelque part pour faire valider par un reviewer? Mais comment? 
Je vais faire une branche pour écrire mon post, sur mon repo. mais le seul maitre à bord c'est moi. 
Est-ce qu'on "forcerai" l'édition d'un post sur le compte du groupe validant les badges? càd Openfab dans ce cas ci. 
on aurai alors une centralisation des "épreuves" au niveau du fablab. 

Mmmm, c'est pas mal ça en fait. 
1. j'ai pris des notes sur mon compte, ou là ou je veux en fait. 
2. Je vais créer une branche pour la validation de mon badge laser sur ce repo (ici donc)
3. validation du pull request par les pairs. (reviewers) 1, 2 ou plus? 
4. ajout du badge sur son portfolio avec un lien vers l'épreuve en question?

**Comment by nicolasdb** [comment]
For Usage1 badge,what about that:
![laser-th](https://user-images.githubusercontent.com/12049360/44899712-cadfbb00-ad02-11e8-8085-92070fe2de8a.jpg)

**Comment by nicolasdb** [comment]
un peu de nouveauté. 

## Comment créer un Open Badge ? 

![image](https://user-images.githubusercontent.com/12049360/66206704-25d7a480-e6b1-11e9-8906-14691414ca56.png)
https://openbadges.info/creer/

https://blogs.lyceecfadumene.fr/informatique/2019/03/27/openbadge-info-decouvrir-les-badges-numeriques-ouverts/
https://openbadgepassport.com/faq-fr/

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/66221481-5a5a5900-e6cf-11e9-9947-20db10731999.png)

version light pour l'article. 
![ob101-th](https://user-images.githubusercontent.com/12049360/66223165-1701e980-e6d3-11e9-885b-12c6be0debd1.jpg)

**Comment by nicolasdb** [comment]
haha, le badge awareness
![image](https://user-images.githubusercontent.com/12049360/66227103-c099a880-e6dc-11e9-8b3a-80e2bc93ab93.png)

**Comment by nicolasdb** [comment]
>La Casemate à mis en place en place un système d’Open Badges pour notamment valoriser l’engagement des publics, certifier des formations, et reconnaître des compétences formelles et informelles à des personnes qui s’engagent dans des actions entre sciences et société.

https://lacasemate.fr/fab-lab-et-co/open-badges/
Ils ont plusieurs badges proposés mais 

![image](https://user-images.githubusercontent.com/12049360/66250970-4ef84380-e74a-11e9-8c7c-2142997df248.png)

**Comment by nicolasdb** [comment]
pour l'instant, le contenu proposé en badge est pas dingue. 
ça semble être très spécifique à chaque organisation, les plateformes se focus sur générer les badges. 

via credly: https://credly.com/u/2163891
description brève, pas de lien vers comment l'obtenir, décevant
![image](https://user-images.githubusercontent.com/12049360/66251182-96340380-e74d-11e9-9584-9866fa525597.png)



~~via OBA: https://www.openbadgeacademy.com/badge/692
C'est pas si mal celui ci mais il y a très peu de badges (pour l'instant) 
Visuel, description et procédure d'obtention avec un lien pour l'obtenir.~~
The Open Badge Academy will be closing on 31st August 2019.

![image](https://user-images.githubusercontent.com/12049360/66251193-b794ef80-e74d-11e9-8398-b39fd81452dc.png)

~~_reste que c'est un peu chiant pour s'inscrire, il faut choisir une "academie" avant de pouvoir s'inscrire, j'ai choisit OBA makers, l'issuer de celui ci, puis j'ai pu m'identifier en utilisant mon compte gmail ou linkdin et reste encore à être validé humainement, probablement par l'Issuer_ 
https://www.openbadgeacademy.com/home~~

~~Je pense qu'on pourrait peut-être s'y faire référencer comme "basic academy" mais il n'y a pas plus d'info, faut les contacter. Je me demande si ça ne fait pas double emploi avec badgr.~~ 
![image](https://user-images.githubusercontent.com/12049360/66251312-20309c00-e74f-11e9-8653-b9ae61e68187.png)


1. en tant qu'Openfab, je pense qu'on doit choisir un mode de validation, badgr, OBA, ou autre. 
Je pense que badgr peux gérer les badges et nous permettre de les attribuer certifié. 
mais ne propose pas de cursus, ha si. les pathways. 
test: 
https://pathways.badgr.io/public/pathway/5d9762c146e0fb002178788b/element/5d9762c146e0fb002178788a

2. mais en tant que "learner/student", on clique, on clique et tant que les "issuers" n'ont pas fait un meilleur boulot, les descriptions et conditions sont très limitées. 

![image](https://user-images.githubusercontent.com/12049360/66251451-8f5ac000-e750-11e9-8ad2-91051f90b1c7.png)
![image](https://user-images.githubusercontent.com/12049360/66251462-997cbe80-e750-11e9-960f-5a7a34d14a04.png)
![image](https://user-images.githubusercontent.com/12049360/66251465-a4375380-e750-11e9-9d44-47b0059d19fe.png)

**Comment by nicolasdb** [comment]
donc si je reprend ceci et que j'essaye de l'appliquer en pathway badgr : 
![skillstree](https://user-images.githubusercontent.com/12049360/44899511-442ade00-ad02-11e8-8e9e-bb306588ef6a.jpg)

1. le sens est inversé. on va vers l'objectif de gagner un badge niveau supérieur qui requière l'obtention de badge inférieur.

**Comment by nicolasdb** [comment]
1. créer un new pathway. WIP Lasercutting Master
2. créer le badge associé. Lasercutting Master
3. shit, définir toutes les étapes. 
![image](https://user-images.githubusercontent.com/12049360/66253037-c89c2b80-e762-11e9-8386-059e4a6e8507.png)
4. créer et définir tout les badges et critères

**Comment by nicolasdb** [comment]
https://dougbelshaw.com/blog/2017/03/31/badging-co-operative-character/

> To conclude, then, I think that badges can be used to develop co-operative character. However, the importance is not the earning of the badge itself, but the way that it evidences the International Principles of Co-operation. Eventually, as with all credentials, the rubber hits the road, and the credential itself, as a proxy for the thing, is no longer required. Credentials are a means to an end.

**Comment by nicolasdb** [comment]
https://howto.p2pu.org/modules/tutorial/start/

> Course in a Box consist of
> -  a tutorial module to guide you through the technical steps for creating your course.
> -  a resource module to help you design content, activities, community and feedback for your course.
> -  a reference module with some explanation and detail about Course in a Box.
> -  a community forum where you can ask questions or share your experience.


c'est un template à forker, du jekyll, sur github. 
C'est tout préparé pour faire une lesson et son contenu.

**Comment by nicolasdb** [comment]
https://weareopen.coop/OB101/modules/how/do/
## How to write good badge criteria
When goal-setting you may have seen the mnenomic SMART used, standing for: Specific, Measurable, Achievable, Relevant and Timely. This is also a useful approach to use when writing badge criteria.

**Specific -** what will the badge earner have accomplished by earning this badge?
**Measurable** - how will the assessor know when the level at which the badge is awarded has been achieved?
**Achievable** - in what ways can the badge be achieved?
**Relevant -** is this badge worth earning? what opportunities does it unlock?
**Timely -** should this badge expire after a certain period of time?

**Comment by nicolasdb** [comment]
## Anatomie d'un Open badge 2017
![image](https://user-images.githubusercontent.com/12049360/66476961-37e18a80-ea97-11e9-82ff-b596d8e35586.png)

https://www.echosciences-normandie.fr/communautes/le-dome/articles/anatomie-d-un-open-badge

## saison 2 
![image](https://user-images.githubusercontent.com/12049360/66477191-c8b86600-ea97-11e9-9660-1ef0451af74a.png)

https://www.echosciences-normandie.fr/articles/des-badges-au-dome-saison-2

J'aime moins, le visuel est plus dense et les variantes sont trop discrètes à mon goût, c'est pas très clair.
